cache:
    directories:
        - $HOME/perl_modules

sudo: false
language: perl
perl:
    - 'blead'
    - '5.26'
    - '5.24'
    - '5.22'
    - '5.20'
    - '5.18'
    - '5.16'
    - '5.14'

matrix:
    allow_failures:
        - perl: 'blead'
    fast_finish: true
before_install:
    - git config --global user.name "TravisCI"
    - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
    - cpanm local::lib
    - eval "$(perl -Mlocal::lib=$HOME/perl_modules)"
install:
    - cpanm --quiet --skip-satisfied Dist::Zilla Pod::Weaver::Section::Support
    - "(cd App-Du-Analyze && dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet)"
    - "(cd App-Du-Analyze && dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose)"
script:
    - "(cd App-Du-Analyze && dzil smoke --release --author)"
